import streamlit as st

st.title("ShubhgeneAI")
st.write(GENE_DATABASE = {
    gene = st.selectbox("Select Gene", list(GENE_DATABASE.keys()))
st.json(GENE_DATABASE[gene])


    "TP53": {
        "gene_name": "TP53",
        "full_name": "Tumor Protein p53",
        "chromosome_location": "17p13.1",
        "gene_type": "Tumor Suppressor",
        "function": "Controls cell cycle, DNA repair, apoptosis",
        "protein_name": "p53 protein",
        "protein_length_aa": 393,
        "molecular_weight_kDa": 53,
        "chemical_nature": "Mixed polar + charged protein",
        "protein_structure": "Tetramer transcription factor",
        "pathways": "Cell cycle checkpoint, apoptosis pathway",
        "expression_site": "Most tissues",
        "mutation_impact": "Loss leads to uncontrolled cell growth",
        "disease_association": "Multiple cancers",
        "biological_role": "Genome stability",
        "cellular_location": "Nucleus",
        "inheritance_pattern": "Autosomal dominant (cancer risk syndromes)",
        "clinical_importance": "Major cancer biomarker",
        "drug_target": "Indirect",
        "research_importance": "Very high"
    },

    "BRCA1": {
        "gene_name": "BRCA1",
        "full_name": "Breast Cancer Type 1",
        "chromosome_location": "17q21",
        "gene_type": "Tumor Suppressor",
        "function": "DNA double strand break repair",
        "protein_name": "BRCA1 protein",
        "protein_length_aa": 1863,
        "molecular_weight_kDa": 220,
        "chemical_nature": "Large acidic protein",
        "protein_structure": "Multi domain repair protein",
        "pathways": "Homologous recombination DNA repair",
        "expression_site": "Breast, ovary",
        "mutation_impact": "High cancer susceptibility",
        "disease_association": "Breast, ovarian cancer",
        "biological_role": "DNA stability maintenance",
        "cellular_location": "Nucleus",
        "inheritance_pattern": "Autosomal dominant",
        "clinical_importance": "Genetic screening marker",
        "drug_target": "PARP inhibitor sensitivity",
        "research_importance": "Very high"
    },

    "EGFR": {
        "gene_name": "EGFR",
        "full_name": "Epidermal Growth Factor Receptor",
        "chromosome_location": "7p11.2",
        "gene_type": "Oncogene",
        "function": "Cell growth signaling receptor",
        "protein_name": "EGFR receptor",
        "protein_length_aa": 1210,
        "molecular_weight_kDa": 134,
        "chemical_nature": "Glycosylated membrane protein",
        "protein_structure": "Transmembrane receptor tyrosine kinase",
        "pathways": "MAPK, PI3K-AKT signaling",
        "expression_site": "Skin, epithelial tissues",
        "mutation_impact": "Cancer cell proliferation",
        "disease_association": "Lung cancer, glioblastoma",
        "biological_role": "Cell growth regulation",
        "cellular_location": "Cell membrane",
        "inheritance_pattern": "Somatic mutation common",
        "clinical_importance": "Drug therapy target",
        "drug_target": "Yes",
        "research_importance": "High"
    },

    "CFTR": {
        "gene_name": "CFTR",
        "full_name": "Cystic Fibrosis Transmembrane Conductance Regulator",
        "chromosome_location": "7q31.2",
        "gene_type": "Transport Protein Gene",
        "function": "Chloride ion channel regulation",
        "protein_name": "CFTR protein",
        "protein_length_aa": 1480,
        "molecular_weight_kDa": 170,
        "chemical_nature": "Membrane glycoprotein",
        "protein_structure": "Ion channel transporter",
        "pathways": "Ion transport regulation",
        "expression_site": "Lungs, pancreas",
        "mutation_impact": "Thick mucus formation",
        "disease_association": "Cystic fibrosis",
        "biological_role": "Fluid balance",
        "cellular_location": "Cell membrane",
        "inheritance_pattern": "Autosomal recessive",
        "clinical_importance": "New gene therapy target",
        "drug_target": "Yes",
        "research_importance": "High"
    },

    "APOE": {
        "gene_name": "APOE",
        "full_name": "Apolipoprotein E",
        "chromosome_location": "19q13.32",
        "gene_type": "Metabolic Gene",
        "function": "Lipid transport and cholesterol metabolism",
        "protein_name": "ApoE protein",
        "protein_length_aa": 299,
        "molecular_weight_kDa": 34,
        "chemical_nature": "Lipid binding protein",
        "protein_structure": "Alpha helix rich",
        "pathways": "Lipoprotein metabolism",
        "expression_site": "Liver, brain",
        "mutation_impact": "Alters lipid transport",
        "disease_association": "Alzheimer risk",
        "biological_role": "Lipid homeostasis",
        "cellular_location": "Secreted protein",
        "inheritance_pattern": "Allele dependent risk",
        "clinical_importance": "Neurodegenerative marker",
        "drug_target": "Indirect",
        "research_importance": "High"
    },

    "HBB": {
        "gene_name": "HBB",
        "full_name": "Hemoglobin Subunit Beta",
        "chromosome_location": "11p15.5",
        "gene_type": "Structural Protein Gene",
        "function": "Oxygen transport in blood",
        "protein_name": "Beta globin",
        "protein_length_aa": 147,
        "molecular_weight_kDa": 16,
        "chemical_nature": "Globular protein",
        "protein_structure": "Alpha helical globin fold",
        "pathways": "Oxygen transport",
        "expression_site": "Red blood cells",
        "mutation_impact": "Abnormal hemoglobin",
        "disease_association": "Sickle cell anemia, thalassemia",
        "biological_role": "Gas transport",
        "cellular_location": "Cytoplasm",
        "inheritance_pattern": "Autosomal recessive",
        "clinical_importance": "Major blood disorder marker",
        "drug_target": "Indirect",
        "research_importance": "High"
    },

    "INS": {
        "gene_name": "INS",
        "full_name": "Insulin",
        "chromosome_location": "11p15.5",
        "gene_type": "Hormone Gene",
        "function": "Regulates blood glucose",
        "protein_name": "Insulin",
        "protein_length_aa": 51,
        "molecular_weight_kDa": 5.8,
        "chemical_nature": "Peptide hormone",
        "protein_structure": "Two chain peptide hormone",
        "pathways": "Glucose metabolism",
        "expression_site": "Pancreas beta cells",
        "mutation_impact": "Glucose imbalance",
        "disease_association": "Diabetes",
        "biological_role": "Metabolic control",
        "cellular_location": "Secreted hormone",
        "inheritance_pattern": "Complex",
        "clinical_importance": "Essential therapeutic hormone",
        "drug_target": "Direct therapy",
        "research_importance": "Very high"
    },

    "VEGFA": {
        "gene_name": "VEGFA",
        "full_name": "Vascular Endothelial Growth Factor A",
        "chromosome_location": "6p21.1",
        "gene_type": "Growth Factor Gene",
        "function": "Blood vessel formation",
        "protein_name": "VEGF-A",
        "protein_length_aa": 232,
        "molecular_weight_kDa": 27,
        "chemical_nature": "Secreted growth factor",
        "protein_structure": "Dimeric growth factor",
        "pathways": "Angiogenesis pathway",
        "expression_site": "Many tissues",
        "mutation_impact": "Abnormal vessel growth",
        "disease_association": "Cancer, macular degeneration",
        "biological_role": "Blood vessel development",
        "cellular_location": "Secreted",
        "inheritance_pattern": "Complex",
        "clinical_importance": "Anti-VEGF drug target",
        "drug_target": "Yes",
        "research_importance": "High"
    },

    "MYC": {
        "gene_name": "MYC",
        "full_name": "MYC Proto-Oncogene",
        "chromosome_location": "8q24.21",
        "gene_type": "Oncogene",
        "function": "Controls cell growth and division",
        "protein_name": "c-Myc",
        "protein_length_aa": 439,
        "molecular_weight_kDa": 49,
        "chemical_nature": "DNA binding transcription factor",
        "protein_structure": "Helix-loop-helix",
        "pathways": "Cell cycle progression",
        "expression_site": "Rapidly dividing cells",
        "mutation_impact": "Tumor formation",
        "disease_association": "Many cancers",
        "biological_role": "Cell proliferation",
        "cellular_location": "Nucleus",
        "inheritance_pattern": "Mostly somatic mutation",
        "clinical_importance": "Cancer prognosis marker",
        "drug_target": "Experimental",
        "research_importance": "Very high"
    },

    "MTHFR": {
        "gene_name": "MTHFR",
        "full_name": "Methylenetetrahydrofolate Reductase",
        "chromosome_location": "1p36.22",
        "gene_type": "Metabolic Enzyme Gene",
        "function": "Folate metabolism",
        "protein_name": "MTHFR enzyme",
        "protein_length_aa": 656,
        "molecular_weight_kDa": 74,
        "chemical_nature": "Enzyme protein",
        "protein_structure": "FAD dependent enzyme",
        "pathways": "Homocysteine metabolism",
        "expression_site": "Liver, brain",
        "mutation_impact": "Homocysteine accumulation",
        "disease_association": "Cardiovascular risk, neural defects",
        "biological_role": "Methylation cycle",
        "cellular_location": "Cytoplasm",
        "inheritance_pattern": "Autosomal recessive variants",
        "clinical_importance": "Nutritional genetics marker",
        "drug_target": "Indirect",
        "research_importance": "Medium"
    }

}

    "Let's start building! For help and inspiration, head over to [docs.streamlit.io](https://docs.streamlit.io/)."
)
